// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPHERqnROAUi-DKzAQl_a6y1Yq_SVLk2U',
    appId: '1:785922349117:web:616d5b49daffbc7b6d7254',
    messagingSenderId: '785922349117',
    projectId: 'fiap-mba-e2db0',
    authDomain: 'fiap-mba-e2db0.firebaseapp.com',
    storageBucket: 'fiap-mba-e2db0.appspot.com',
    measurementId: 'G-XF6GWT808T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08kgyN6tz1MQxyXnTleoiv7JwcL7Ppv8',
    appId: '1:785922349117:android:edb677c6eb8374366d7254',
    messagingSenderId: '785922349117',
    projectId: 'fiap-mba-e2db0',
    storageBucket: 'fiap-mba-e2db0.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-OFVZXuD6GtBXCyahTe0THx08h0CIMT0',
    appId: '1:785922349117:ios:57745d000fe4cf5b6d7254',
    messagingSenderId: '785922349117',
    projectId: 'fiap-mba-e2db0',
    storageBucket: 'fiap-mba-e2db0.appspot.com',
    iosClientId: '785922349117-4gsp4inf1ugvcol861ki6opmloj7s15q.apps.googleusercontent.com',
    iosBundleId: 'br.com.fiap.hwMobiledevelopmentMoneycontrol',
  );
}
